// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mimbiqrdprnwudmutsqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pbWJpcXJkcHJud3VkbXV0c3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDc0MzgsImV4cCI6MjA2MDYyMzQzOH0.zdOj4ZLLDUikavgo_LXwgAEGFMplUoC5Aqh0ckXATmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);